# Generated by Django 5.2.4 on 2025-07-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Zamanı')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('RUNNING', 'Eğitiliyor'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Hata Oluştu')], default='PENDING', max_length=10, verbose_name='Durum')),
                ('dataset_zip', models.FileField(upload_to='datasets/', verbose_name='Veri Seti (.zip)')),
                ('selected_model', models.CharField(choices=[('yolov8n', 'YOLOv8n (Hızlı, Düşük Başarı)'), ('yolov8s', 'YOLOv8s'), ('yolov8m', 'YOLOv8m'), ('yolov10n', 'YOLOv10n (Yeni, Hızlı)'), ('yolov10s', 'YOLOv10s')], max_length=20, verbose_name='Seçilen Model')),
                ('epochs', models.PositiveIntegerField(default=10, verbose_name='Epoch Sayısı')),
                ('dataset_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Çıkarılan Veri Seti Yolu')),
                ('results_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sonuçların Yolu')),
            ],
        ),
    ]
