# Generated by Django 5.2.4 on 2025-07-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingjob',
            name='selected_model',
            field=models.CharField(choices=[('yolov8n', 'YOLOv8n (Aktif)'), ('yolov8s', 'YOLOv8s (Aktif)'), ('yolov8m', 'YOLOv8m (Aktif)'), ('yolov10n', 'YOLOv10n (Aktif)'), ('yolov10s', 'YOLOv10s (Aktif)'), ('yolov4_show', 'YOLOv4 (Yakında)'), ('yolov5_show', 'YOLOv5 (Aktif)'), ('yolov6_show', 'YOLOv6 (Aktif)'), ('yolov7_show', 'YOLOv7 (Yakında)'), ('yolov9_show', 'YOLOv9 (Yakında)'), ('yolov11_show', 'YOLOv11 (Aktif)'), ('yolov12_show', 'YOLOv12 (Aktif)')], max_length=20, verbose_name='Seçilen Model'),
        ),
    ]
